# Generated by Django 2.2.12 on 2020-05-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200508_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Category'),
        ),
    ]
