# Generated by Django 2.2.12 on 2020-05-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20200508_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='frontend.Category'),
        ),
    ]
